# Generated by Django 4.0.2 on 2022-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE'), ('ON MODERATION', 'ON MODERATION'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=16),
        ),
    ]
