# Generated by Django 4.0.2 on 2022-03-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_status_alter_post_tags'),
        ('posts', '0012_alter_post_status'),
    ]

    operations = [
    ]
